### ISSUE TITLE
Collect Transponder Code (or squawk) or successive values of Transponder Code

### ISSUE THREAD

**Issue by TheSharedCockpit** [phpvms/acars#37]
Hello,

In data returned by an API call to **api/acars** the value "transponder" is always null.
Is there any chance to have that value collected and rendered accessible to api/acars calls?

CF. https://discord.com/channels/332920618729340929/1126591018997911633/1174719092578582620

Thank You,

Didier

**Comment by nabeelio** [comment]
This should be working now
