### ISSUE TITLE
Engine Start/Stop logging messages with engine on

### ISSUE THREAD

**Issue by avs-code** [phpvms/acars#42]
In propeller aircraft, if the engine is idle at low rpm, is considered engine stop.

This behaviour must be checked and tuning to 0 rpm = engine stop or similar.

**Comment by nabeelio** [comment]
The calculation is done based on fuel flow. I'm planning to bring this into the aircraft configuration

**Comment by avs-code** [comment]
OK, that explains why it's with small aircraft, they have very little fuel flow at idle. Thanks!
