### ISSUE TITLE
Additional aircraft features

### ISSUE THREAD

**Issue by nabeelio** [phpvms/acars#43]
- APU
- Doors
- Seatbelts
- Emergency lights
- Anti-ice

**Comment by FatihKoz** [comment]
* Battery
* Packs (or Bleeds)

**Comment by avs-code** [comment]
- air conditionen/cabin presure?

**Comment by nabeelio** [comment]
Yeah if cabin pressure can be then converted into a true/false, that could work

**Comment by FatihKoz** [comment]
That will be tricky :) Pressure is either calculated or reported back by the sim, I am not sure that we can make a boolean from it 😸

**Comment by FatihKoz** [comment]
If it is not too much work, we should consider adding the **Bleeds** to that list too @nabeelio please.

Even though they are part of the main pressurization system, they are different, bleeds can be on but packs can be off. Or vice versa you can leave packs on but turn all bleeds off (engine 1/2/apu). The result will be same though (non working pressurization system) but the effects will be different 😉
